destination: _site/
url: "http://127.0.0.1:4012"
baseurl: "/Otherguide-pdf"
port: 4012
output: pdf
product: Other Guide
print_title: Other Guide
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: other_skills_sidebar
