destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/UNIXguide-pdf"
port: 4010
output: pdf
product: UNIX Guide
print_title: Intoduction to UNIX
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: UNIX_guide_sidebar
