destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/Rguide-pdf"
port: 4011
output: pdf
product: R Guide
print_title: R Guide
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: Rguide_sidebar
