destination: _site/
url: "http://127.0.0.1:4012"
baseurl: "/Analysisguide-pdf"
port: 4012
output: pdf
product: Analysis
print_title: Analysis Guide
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: Analysis_sidebar
